# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bd695429c476f3000d6267696d00e46bff3e3c751f4b962a4ddb5c4c10b8acf33feee475219f7cea8980b9053bf08cdc55363c6b8b5cc933506d952e7b1179

test:
  secret_key_base: 416c946e00260bbc2180c3de353f5870930ee6d9806dcb3327e1c8046d28a7d71a53e91f8672e6af4335b347bcfde4eaeabeb5900962b43dd5f6071cd85a880e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
